### ISSUE TITLE
run in gpu

### ISSUE THREAD

**Issue by handamn** [Hyuto/yolov7-node#2]
is it possible to run this in gpu, i've searching to use onnxruntime-web, but i still have no idea to convert it. anny suggestion? thanks

**Comment by Hyuto** [comment]
Hello, currently it's not possible to run on GPU using `onnxruntime` with node. The alternative is using python, c, cpp, c# or java since `onnxruntime-gpu` is supported on those programming language. But if you insist to do this on node you can use GPU using [`tfjs-node-gpu`](https://www.tensorflow.org/js/guide/nodejs#tensorflow_gpu). It's tensorflow so you have to convert onnx model to `tfjs` format beforehand using [onnx2tf](https://github.com/onnx/onnx-tensorflow#use-cli). I'm not guarantee the last will work flawlessly.

**Comment by Hyuto** [comment]
Since there's no problem left, I'm closing this issue.
